{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.1.jar",
          "url": "guilib-26.1.2-fabric-0.12.1.jar",
          "size": 3357800,
          "sha512": "34586703faf023a22393c49445d48bc4f3a950b29609cdadd9757afca4cd46e212483aaf622c57f4b9e33630a927ee6626938727eb5f3aaf84cdf987d3a70498",
          "sha256": "77283889bf9a1262db642fb48679255ce148ab3b283ed71bcd45df9edcd24d1b",
          "sha1": "b3e5125285f6483bcf866a060a7a08a690d08003",
          "md5": "5a344e2cd4e4e8983c98662d5c0362d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.1.jar",
          "url": "guilib-26.1.2-fabric-0.12.1.jar",
          "size": 3357800,
          "sha512": "34586703faf023a22393c49445d48bc4f3a950b29609cdadd9757afca4cd46e212483aaf622c57f4b9e33630a927ee6626938727eb5f3aaf84cdf987d3a70498",
          "sha256": "77283889bf9a1262db642fb48679255ce148ab3b283ed71bcd45df9edcd24d1b",
          "sha1": "b3e5125285f6483bcf866a060a7a08a690d08003",
          "md5": "5a344e2cd4e4e8983c98662d5c0362d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.1-sources.jar",
          "url": "guilib-26.1.2-fabric-0.12.1-sources.jar",
          "size": 1545277,
          "sha512": "55c4de2c3144125835bc608a6a7bba3b2ecc258c5835f45a5b3c8ee8ed02612bb7a723a978638f5b9c6294b07be8778e291648c80a0e0fb9bd577f09a6688c64",
          "sha256": "dce31e21cef9dc967b62044fc0d4113d25f2396e74eba503a6584aba9cf442ef",
          "sha1": "85bfa659bdafc32656f9890853c5e3ac83e857e5",
          "md5": "da77be92f7a3d0075ed7a4dce1383c32"
        }
      ]
    }
  ]
}
