{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.5.0.jar",
          "url": "guilib-26.1.2-fabric-0.5.0.jar",
          "size": 3027480,
          "sha512": "8c257e3f6f80d2bc35973c975e3b2761a9e01e6d251ff230434e5f4ff868bf3abfbc99d0fa2706b81e56646419c0efe09af48df8b5a7bf5b2bc3b1564082f9ed",
          "sha256": "48da57bc7b3f26757836d9cd5d9ab0872f462f2d853eda67ad8073817ab6806c",
          "sha1": "7683db0323f391188d352956ad6fa30fc7b7c896",
          "md5": "5440cac5089218b3d0fd4ae9897319c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.5.0.jar",
          "url": "guilib-26.1.2-fabric-0.5.0.jar",
          "size": 3027480,
          "sha512": "8c257e3f6f80d2bc35973c975e3b2761a9e01e6d251ff230434e5f4ff868bf3abfbc99d0fa2706b81e56646419c0efe09af48df8b5a7bf5b2bc3b1564082f9ed",
          "sha256": "48da57bc7b3f26757836d9cd5d9ab0872f462f2d853eda67ad8073817ab6806c",
          "sha1": "7683db0323f391188d352956ad6fa30fc7b7c896",
          "md5": "5440cac5089218b3d0fd4ae9897319c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.5.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.5.0-sources.jar",
          "size": 1464717,
          "sha512": "6d5dc337bc93cfb29b1996f547ac1adb37c5936e4ecdba520a07e94890d7a09df7fd6833680a33ce2ee4c362fa81f01e5acd072f6683bb9496c84a267945fda6",
          "sha256": "2603b9f801efab261da8031861e83832712b2095b9dbde284d57981bcb35cf8c",
          "sha1": "d1072caeb53cb600f8de47f279e906f7b60e5461",
          "md5": "ff27df60718ed63238740e2be8e6f782"
        }
      ]
    }
  ]
}
