{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.11.0.jar",
          "url": "guilib-26.1.2-fabric-0.11.0.jar",
          "size": 3310023,
          "sha512": "055c1406ac973e9f124a8c43edccb39fa6f8b0cb084d15915f7e94e481ec775e5da549999ef0e49e982a1160a92287641e7c5674497309a7f65e745bafa995ad",
          "sha256": "ce917b1b0b886c9faaa212b62a10dba0065c8184e7fded9d1f7e2c1c878e8e9e",
          "sha1": "8b32bbf7307e765b9fb62e5d464d978f4e828e14",
          "md5": "5fc734afc5650245569cdca40f610b42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.11.0.jar",
          "url": "guilib-26.1.2-fabric-0.11.0.jar",
          "size": 3310023,
          "sha512": "055c1406ac973e9f124a8c43edccb39fa6f8b0cb084d15915f7e94e481ec775e5da549999ef0e49e982a1160a92287641e7c5674497309a7f65e745bafa995ad",
          "sha256": "ce917b1b0b886c9faaa212b62a10dba0065c8184e7fded9d1f7e2c1c878e8e9e",
          "sha1": "8b32bbf7307e765b9fb62e5d464d978f4e828e14",
          "md5": "5fc734afc5650245569cdca40f610b42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.11.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.11.0-sources.jar",
          "size": 1531352,
          "sha512": "120430f6b8e4a4b68ea14ddefe9d496fddbc76b6d210e97a7821ee9bdc202d4a5a3157424d9f04e5817020bae071af73116892fda433d23ee5849b9e248c2ba5",
          "sha256": "de4fcb9959fcf85d1effb90563f869203b108f853dc67bfc6280b21698df0c16",
          "sha1": "807a29235fcc9fb24fbf3dadc1ca0863418edfc7",
          "md5": "3a1d96a58d8be65fa33a20016f8ceb75"
        }
      ]
    }
  ]
}
