{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.9.0.jar",
          "url": "guilib-26.1.2-fabric-0.9.0.jar",
          "size": 3116367,
          "sha512": "0ef6d6bfa2b102cb8b0a0dee48a0b4fdf852612429e7d7073847a0bf28cb5f92eeec2a83849f323b925d891e238d4bad8985712698c0a5c02a4ed49f6425f93e",
          "sha256": "0a79b60a108f244f9ea2d7582d04ca672a162d4a76d708f2f3efbbc0bc582e76",
          "sha1": "885126df01c1275d228140464701d5c58e69492b",
          "md5": "22a3e31bad0bc43f14a16dfdcf08eb0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.9.0.jar",
          "url": "guilib-26.1.2-fabric-0.9.0.jar",
          "size": 3116367,
          "sha512": "0ef6d6bfa2b102cb8b0a0dee48a0b4fdf852612429e7d7073847a0bf28cb5f92eeec2a83849f323b925d891e238d4bad8985712698c0a5c02a4ed49f6425f93e",
          "sha256": "0a79b60a108f244f9ea2d7582d04ca672a162d4a76d708f2f3efbbc0bc582e76",
          "sha1": "885126df01c1275d228140464701d5c58e69492b",
          "md5": "22a3e31bad0bc43f14a16dfdcf08eb0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.9.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.9.0-sources.jar",
          "size": 1488309,
          "sha512": "5ec2ad059e5e682092938e64303e35669351d68547e4f14ce7b54db0bcb75dfa0b5be9a8780e037005c42062a579b9bda2a81e52f88d3bfce182e9f13589c91e",
          "sha256": "026a73f70863d58b3217d0a380453796c56a3dc00dc9589205720bacedf53ec2",
          "sha1": "312d041fbef1f9c3ad77d9bc0e45249e8a7886a1",
          "md5": "17768e8514e49173b963643b5e06a208"
        }
      ]
    }
  ]
}
