{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.5.jar",
          "url": "guilib-26.1.2-fabric-0.12.5.jar",
          "size": 3384501,
          "sha512": "0cde6141795b15fdc39dcb591441a803adf68319ae01e96ac5566ccd4c8a64a627fbef029fc7890d67c96cd4854ef7db7fc5884eb72c2a0847cc719bd2c70e41",
          "sha256": "f0eb33d56daa1b9d0fcdcece88e8164fefecf6e9cf369bd86bbced7b3a7ab49a",
          "sha1": "37f3bb6fc3059bd65c532232daf51e554baabcda",
          "md5": "ba723d955d6d49bcc1821fe604c9808a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.5.jar",
          "url": "guilib-26.1.2-fabric-0.12.5.jar",
          "size": 3384501,
          "sha512": "0cde6141795b15fdc39dcb591441a803adf68319ae01e96ac5566ccd4c8a64a627fbef029fc7890d67c96cd4854ef7db7fc5884eb72c2a0847cc719bd2c70e41",
          "sha256": "f0eb33d56daa1b9d0fcdcece88e8164fefecf6e9cf369bd86bbced7b3a7ab49a",
          "sha1": "37f3bb6fc3059bd65c532232daf51e554baabcda",
          "md5": "ba723d955d6d49bcc1821fe604c9808a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.5-sources.jar",
          "url": "guilib-26.1.2-fabric-0.12.5-sources.jar",
          "size": 1552623,
          "sha512": "c2265231dd13d2377db8dd852b3bbfd171417da970524283c9c365906ea048dcb5856498a6d4e3f3400f40de613c08fe9ff435796928eb3e069d3b148b028766",
          "sha256": "379fac18eec959e4635233a02bcd64e9c55828d90d5d375e8d8aded93d5b1035",
          "sha1": "1bd7dec3c5506c7035b7efa535392efc5db26f75",
          "md5": "c91bf839b61b6d7efe8aa58a552c6abd"
        }
      ]
    }
  ]
}
