{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.0.jar",
          "url": "guilib-26.2-fabric-0.12.0.jar",
          "size": 3351846,
          "sha512": "5b1401b6073fdc5d6e634aaf8e6b3d501fc73f5320c6f55d7aaa5110976e114b3e9f4d992aff06c1f1996a1b7db3544ceb7d7caebeff7c1a6932d0841b31535c",
          "sha256": "2fe736e4d1a6bb12c0eb9287d4800af482b2c4cf395a40cdfbce9a801a266c86",
          "sha1": "80ef827437e52c5e7bcbaacf190d2badea1675c4",
          "md5": "1f18b6bfc37921e630779940e60b0c38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.0.jar",
          "url": "guilib-26.2-fabric-0.12.0.jar",
          "size": 3351846,
          "sha512": "5b1401b6073fdc5d6e634aaf8e6b3d501fc73f5320c6f55d7aaa5110976e114b3e9f4d992aff06c1f1996a1b7db3544ceb7d7caebeff7c1a6932d0841b31535c",
          "sha256": "2fe736e4d1a6bb12c0eb9287d4800af482b2c4cf395a40cdfbce9a801a266c86",
          "sha1": "80ef827437e52c5e7bcbaacf190d2badea1675c4",
          "md5": "1f18b6bfc37921e630779940e60b0c38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.0-sources.jar",
          "url": "guilib-26.2-fabric-0.12.0-sources.jar",
          "size": 1542697,
          "sha512": "4fbcc77366a968e3385d1a570acf85f90d764c933ab88293341df07cfb9dfdfc9991d1257a82b75bfdf36d006df03d14c554459c7434244edb423a00c07156ea",
          "sha256": "39ea39d41a298322db65faba59af678056b9d58711248473d31beedcb3ce600b",
          "sha1": "a0d20362852ca5d9b3a96218930e4f3359a9e521",
          "md5": "443201df988238f87195b04cbbbe07ec"
        }
      ]
    }
  ]
}
