{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.3.0.jar",
          "url": "guilib-26.2-fabric-0.3.0.jar",
          "size": 2878569,
          "sha512": "e6a438efe889b5ab5a40938775afeac2dea5687b7cbebc4413299afd85167f945d0f3e31c4a3fd01ec115c5397e14aa3984b3e4aa962f7b9b32617160283052e",
          "sha256": "31ced9b3a28599442fb9a2ecb32dc5b9214931d1815024969e8ceb58eeca78f4",
          "sha1": "824ab91745c0c7c9bbcc3d323b6c2d2a8feaf919",
          "md5": "e183250f6277f0036a0fedab35a14441"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.3.0.jar",
          "url": "guilib-26.2-fabric-0.3.0.jar",
          "size": 2878569,
          "sha512": "e6a438efe889b5ab5a40938775afeac2dea5687b7cbebc4413299afd85167f945d0f3e31c4a3fd01ec115c5397e14aa3984b3e4aa962f7b9b32617160283052e",
          "sha256": "31ced9b3a28599442fb9a2ecb32dc5b9214931d1815024969e8ceb58eeca78f4",
          "sha1": "824ab91745c0c7c9bbcc3d323b6c2d2a8feaf919",
          "md5": "e183250f6277f0036a0fedab35a14441"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.3.0-sources.jar",
          "url": "guilib-26.2-fabric-0.3.0-sources.jar",
          "size": 1425614,
          "sha512": "c79fcd34becef5630fea6f4126def391f291e444a92060cf69daca05caccfa627c00a3be15e2893d2b5fec5c5461d69ab1dc49654f985a75754481e1847920e7",
          "sha256": "af654ce618022cbd8797e7a267e6b0a51a0658aac03935dc39d1c2efeda8621e",
          "sha1": "363b0e143e7f91ff3917a57a51a5bc4ca244619c",
          "md5": "07a5569619e6ec34d60bc0dfa17a52e0"
        }
      ]
    }
  ]
}
