{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.3.jar",
          "url": "guilib-26.1.2-fabric-0.4.3.jar",
          "size": 2983706,
          "sha512": "c54e4b34baee292efc5ec3d4b34368b9b4e9105b228d837885aea78ab4565d3dcb0154b78f33a6204c209a2950f3a7b2930ed7e39b907568bfd05f90125284d7",
          "sha256": "4810268079f4f07379a05f20b4d5aa147c749996dfaece14c903b43484898e44",
          "sha1": "02261ca5901d218ceb6f6ed742f3c927f9bee50d",
          "md5": "9ff406d0e0f52e6a2b97394afa2bfb8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.3.jar",
          "url": "guilib-26.1.2-fabric-0.4.3.jar",
          "size": 2983706,
          "sha512": "c54e4b34baee292efc5ec3d4b34368b9b4e9105b228d837885aea78ab4565d3dcb0154b78f33a6204c209a2950f3a7b2930ed7e39b907568bfd05f90125284d7",
          "sha256": "4810268079f4f07379a05f20b4d5aa147c749996dfaece14c903b43484898e44",
          "sha1": "02261ca5901d218ceb6f6ed742f3c927f9bee50d",
          "md5": "9ff406d0e0f52e6a2b97394afa2bfb8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.3-sources.jar",
          "url": "guilib-26.1.2-fabric-0.4.3-sources.jar",
          "size": 1455269,
          "sha512": "98b44b8af67d0004f2596f7d5bf93d25a1c36783065d1005424a74d8042dd3401c8ede9b9eefec4e84ef61c8ec71f1249220022f3d5c9e947bc5367e881b7fa8",
          "sha256": "30916c6630cc5200cb5069c2bf574aefd71fca2040e87b97bedbb7da358c9a63",
          "sha1": "5fc5ffdce7acb1fa2d5a3fe10c49fe61c4d85a53",
          "md5": "4cc64922b2ef77d192e1d70347ec9636"
        }
      ]
    }
  ]
}
