{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.1.jar",
          "url": "guilib-26.1.2-fabric-0.4.1.jar",
          "size": 2981945,
          "sha512": "29f171e15c0bfe67a342f686784ad1e927234c8901afdbc63fb1da592cd2d3688981f7964331aabf3d480c9f754e020202cfb61a5a290a825969fc319aeebba5",
          "sha256": "9cfb01fc0490c16bd04fc668be8bfb7606979d247fec79380b4df7c6b8275dc6",
          "sha1": "98406a904c2c9537f55f1ba76efa7d476463c547",
          "md5": "a9bd07327cc1a21ec9d08a5064d1ce28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.1.jar",
          "url": "guilib-26.1.2-fabric-0.4.1.jar",
          "size": 2981945,
          "sha512": "29f171e15c0bfe67a342f686784ad1e927234c8901afdbc63fb1da592cd2d3688981f7964331aabf3d480c9f754e020202cfb61a5a290a825969fc319aeebba5",
          "sha256": "9cfb01fc0490c16bd04fc668be8bfb7606979d247fec79380b4df7c6b8275dc6",
          "sha1": "98406a904c2c9537f55f1ba76efa7d476463c547",
          "md5": "a9bd07327cc1a21ec9d08a5064d1ce28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.4.1-sources.jar",
          "url": "guilib-26.1.2-fabric-0.4.1-sources.jar",
          "size": 1454578,
          "sha512": "ec3612252c92a9860e2d04576674eab5f8055621355a11c9500d3b78da799a38d3587e53f0550077eefa604ecbb39330cb8d35fe6220d2ae0975cc8c626e48fe",
          "sha256": "4a999630edcbefda91710433ded4b34673caea0aba410a1e89da12f7ed7305c8",
          "sha1": "895cd5369e68ef3ba98bb6b2bb5afc13284b5a0b",
          "md5": "91152e969c3815b3f58c03b3e5f4a705"
        }
      ]
    }
  ]
}
