{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.3-fabric",
    "version": "0.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.5.jar",
          "url": "guilib-26.3-fabric-0.12.5.jar",
          "size": 3383772,
          "sha512": "512acd64c56c593f8f86cf62c549992435fcffc9a3ccdd73869f24dffc5b085a7d5214955aa6775b7996f92decf2f62bd758bf62a1b882367c18608a0ab82b37",
          "sha256": "a8309665c8f929004f74c7d16e886751467c499b3d60f4c18fcc1b8d2876c90c",
          "sha1": "287ae534651cf5d05b69ade75448029726499512",
          "md5": "e388e7fd1b237a650d05713eef8ed0ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.5.jar",
          "url": "guilib-26.3-fabric-0.12.5.jar",
          "size": 3383772,
          "sha512": "512acd64c56c593f8f86cf62c549992435fcffc9a3ccdd73869f24dffc5b085a7d5214955aa6775b7996f92decf2f62bd758bf62a1b882367c18608a0ab82b37",
          "sha256": "a8309665c8f929004f74c7d16e886751467c499b3d60f4c18fcc1b8d2876c90c",
          "sha1": "287ae534651cf5d05b69ade75448029726499512",
          "md5": "e388e7fd1b237a650d05713eef8ed0ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.5-sources.jar",
          "url": "guilib-26.3-fabric-0.12.5-sources.jar",
          "size": 1552503,
          "sha512": "40a99c1866dc6a7e9b43cc710e7f915a0eb6c3feeb8579a544e1dbedd7fa816ea6bcde1bdd9c07e9d5386b5022001dfc49b4dbd5e93db8416324d55004313b24",
          "sha256": "96a4a3099cbb7ef2763e964da3d0bdfae9bf13ad5b73ffc733547865838f0af3",
          "sha1": "bfa7e0f32c366a045baf6ec718c33f829537491b",
          "md5": "11b6e96bb530709e1cdde6cfa95133af"
        }
      ]
    }
  ]
}
