{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.3.0.jar",
          "url": "guilib-26.1.2-fabric-0.3.0.jar",
          "size": 2879295,
          "sha512": "842d4eb5fe189d9dead313a664a5889b9a2321660c4993d9180069984b6e4bf25b98ea037f574a822df689854ec20abd094a0c6c397518381500937634b0a5cf",
          "sha256": "c67507c99ed22a1019b9c732866a45044f038472d0ee61a591235d4d40e1bce5",
          "sha1": "35cb97921bba60f0ae76dc5179157d3b229073f2",
          "md5": "479f5bf0dabf332966d3002b8e218613"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.3.0.jar",
          "url": "guilib-26.1.2-fabric-0.3.0.jar",
          "size": 2879295,
          "sha512": "842d4eb5fe189d9dead313a664a5889b9a2321660c4993d9180069984b6e4bf25b98ea037f574a822df689854ec20abd094a0c6c397518381500937634b0a5cf",
          "sha256": "c67507c99ed22a1019b9c732866a45044f038472d0ee61a591235d4d40e1bce5",
          "sha1": "35cb97921bba60f0ae76dc5179157d3b229073f2",
          "md5": "479f5bf0dabf332966d3002b8e218613"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.3.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.3.0-sources.jar",
          "size": 1425614,
          "sha512": "25e504e6a51baf6ea3cc49a8a05a5ad19cee03ecdc8ae29678e20b28db5a9dd797fb2865a37101164719884b5c232297b7fc1c439f2a903cd785742225aa6980",
          "sha256": "4579ca122d7472fe8dff9c463f6e95f989a81c543ae2a279226bc6bd8abe0ebc",
          "sha1": "3d59ef824ae8a2b6ca1a56c70c96e7889169ca01",
          "md5": "c4f510c8a68c534399e5139541794a39"
        }
      ]
    }
  ]
}
