{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.10.0.jar",
          "url": "guilib-26.1.2-fabric-0.10.0.jar",
          "size": 3145448,
          "sha512": "bce9902bbfc67a2e8973df1fdf8b61f709648a3682eaedbd670ac18932836fe7a6206a3be707af4e2bdad0bfe3101286283ed4115cd5f7691cfead0cdebf55a2",
          "sha256": "e8761ec899a449e4274494665138ff7b890407ea49de74fa3c31e048aaa0623e",
          "sha1": "8882e61e788951309151933c21261cd07291658d",
          "md5": "4d867a89b6ce87c35a3e0557f4b6f47f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.10.0.jar",
          "url": "guilib-26.1.2-fabric-0.10.0.jar",
          "size": 3145448,
          "sha512": "bce9902bbfc67a2e8973df1fdf8b61f709648a3682eaedbd670ac18932836fe7a6206a3be707af4e2bdad0bfe3101286283ed4115cd5f7691cfead0cdebf55a2",
          "sha256": "e8761ec899a449e4274494665138ff7b890407ea49de74fa3c31e048aaa0623e",
          "sha1": "8882e61e788951309151933c21261cd07291658d",
          "md5": "4d867a89b6ce87c35a3e0557f4b6f47f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.10.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.10.0-sources.jar",
          "size": 1498132,
          "sha512": "921fb4d25b053db9ca32c79bbff72e2eb5a46c459cf7faf9cabe728d0b936314cd11c11d580e0abc26ff2b876e25cddeee838c162f9ba9c6fb865f32e4aa9b4d",
          "sha256": "dce31a008469a9aebe33146d463fbb14879ba7974d63320ba0474c1526be2886",
          "sha1": "e24781449dd3667dae431c4ee4650ed0bc2c425c",
          "md5": "bb4316ddb8d87e31cf187effdf3f69c4"
        }
      ]
    }
  ]
}
