{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.8.0.jar",
          "url": "guilib-26.1.2-fabric-0.8.0.jar",
          "size": 3116010,
          "sha512": "e9339c59ccb16ac139511078580a8c80c26977655b0f57aea8ce154f251979f6977f9e6d5bdcb992eacb999609728a7429295db4295fe55353f804869d7e0e41",
          "sha256": "b9131189360f229f761c44088878cd975ff61c7f73d63314233f1cb550c52479",
          "sha1": "8151ced279fc22fe3672a6d0718d34090d7bc7e4",
          "md5": "7652c032b4ed8c8a4a569142873e8dc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.8.0.jar",
          "url": "guilib-26.1.2-fabric-0.8.0.jar",
          "size": 3116010,
          "sha512": "e9339c59ccb16ac139511078580a8c80c26977655b0f57aea8ce154f251979f6977f9e6d5bdcb992eacb999609728a7429295db4295fe55353f804869d7e0e41",
          "sha256": "b9131189360f229f761c44088878cd975ff61c7f73d63314233f1cb550c52479",
          "sha1": "8151ced279fc22fe3672a6d0718d34090d7bc7e4",
          "md5": "7652c032b4ed8c8a4a569142873e8dc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.8.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.8.0-sources.jar",
          "size": 1486307,
          "sha512": "e7a0d8ab627a6542c014f21bda8f0bb58193070e4bd59ef230dba07beec03b654b07a20581b25681d8bcba9e82befc0760e192bc5365e7f7a2caa6fbbf593c2e",
          "sha256": "45c1a4088077dd6e5ade2dc9f3e57ced4b673ea1832b3dcc569fbe93ee997842",
          "sha1": "3ae168dff7fe99ab6e63935eaebc84c0a446fc33",
          "md5": "3a920e1ea445ff77f8e0a7560ac39fdc"
        }
      ]
    }
  ]
}
