{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.2.0.jar",
          "url": "guilib-26.2-fabric-0.2.0.jar",
          "size": 2671858,
          "sha512": "4033ac453ad545f5bda74ce9f937424539a08f6ddcc3429799129fe3ffdbd61163b287b7701956e1b2f2416208956f825d91f72bd3e9bf5e361f29b1d3c9382d",
          "sha256": "39214eefadde39e7f188aa4e44df38a98f5d4e882857fb3712ed0c755d7ed03e",
          "sha1": "c43c7c032f1054f38003a8628f61600b93fc558e",
          "md5": "d6d6be02caf24d46cec81d3ba45415e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.2.0.jar",
          "url": "guilib-26.2-fabric-0.2.0.jar",
          "size": 2671858,
          "sha512": "4033ac453ad545f5bda74ce9f937424539a08f6ddcc3429799129fe3ffdbd61163b287b7701956e1b2f2416208956f825d91f72bd3e9bf5e361f29b1d3c9382d",
          "sha256": "39214eefadde39e7f188aa4e44df38a98f5d4e882857fb3712ed0c755d7ed03e",
          "sha1": "c43c7c032f1054f38003a8628f61600b93fc558e",
          "md5": "d6d6be02caf24d46cec81d3ba45415e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.2.0-sources.jar",
          "url": "guilib-26.2-fabric-0.2.0-sources.jar",
          "size": 1378138,
          "sha512": "e3180cc6910fafd7fb08c8f3ce381b521cc7198a8e111e1093c125e3241450629afa4d75228596acaa91f6e610b11e1b8af5fa6945747d3923c105870bdf1a9a",
          "sha256": "742380d1320f1ff080806db00b6deff25b6b8f99096ebe99cf6f329528a68ab2",
          "sha1": "e6e2f35bac81b61f25498835a4b99237b65678a9",
          "md5": "90905909ff0caf8aedec7c79c462da2b"
        }
      ]
    }
  ]
}
