{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.1.1.jar",
          "url": "guilib-26.2-fabric-0.1.1.jar",
          "size": 2470195,
          "sha512": "89ad0d5f5218b0ad55261b8a187a286ab67071206cf09ef23afb03f221393e59fc314101fd6ed66c8128a66973b6810b66e773b7df0661758abe4f8de074c37f",
          "sha256": "5b4399afed0b2de37ae4b8df8a11cea7e3e63fbc6a2b3466c6e88f7e5918da46",
          "sha1": "10f112a428e9fdea1e3c016d6f90f8e0cd89250e",
          "md5": "7f65a8e9ea20516fde2b560e4a33620c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.1.1.jar",
          "url": "guilib-26.2-fabric-0.1.1.jar",
          "size": 2470195,
          "sha512": "89ad0d5f5218b0ad55261b8a187a286ab67071206cf09ef23afb03f221393e59fc314101fd6ed66c8128a66973b6810b66e773b7df0661758abe4f8de074c37f",
          "sha256": "5b4399afed0b2de37ae4b8df8a11cea7e3e63fbc6a2b3466c6e88f7e5918da46",
          "sha1": "10f112a428e9fdea1e3c016d6f90f8e0cd89250e",
          "md5": "7f65a8e9ea20516fde2b560e4a33620c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.1.1-sources.jar",
          "url": "guilib-26.2-fabric-0.1.1-sources.jar",
          "size": 1339998,
          "sha512": "7aef2f160edbbf61eefc0ecd95910894510558964136412b540b195ec3c3128f2af9db8b5c43d09fec1438a0aa1fa6557a60682f0bb1c8b1cfddcb0e7bea8562",
          "sha256": "aeecba8095ce050443a028232dbbc452f94a4cc9ba3c1912e25d1ac06d2f4328",
          "sha1": "a5d19425090867d903d6cde3bee913dcbe6fa2b8",
          "md5": "c6d63cdf474f8d320c1a31596b6044f8"
        }
      ]
    }
  ]
}
