{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.3-fabric",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.11.0.jar",
          "url": "guilib-26.3-fabric-0.11.0.jar",
          "size": 3310109,
          "sha512": "ae89b6d11216127d58bea657cb4bc7bab2e09f750453e8d864154ff6a915e7db35304d8cdcd0afdf92376096c7ec2c7eecc7e16fb65e0c2f9fdb57aec89d256b",
          "sha256": "506e2964779166007a9515869180605cd785fcd815e0f382d12a6f062332e65d",
          "sha1": "3bc5b8f6dc031e5b4c828c749d663eeaa98bb4c8",
          "md5": "663f91059eca6de486583a96acf319e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.11.0.jar",
          "url": "guilib-26.3-fabric-0.11.0.jar",
          "size": 3310109,
          "sha512": "ae89b6d11216127d58bea657cb4bc7bab2e09f750453e8d864154ff6a915e7db35304d8cdcd0afdf92376096c7ec2c7eecc7e16fb65e0c2f9fdb57aec89d256b",
          "sha256": "506e2964779166007a9515869180605cd785fcd815e0f382d12a6f062332e65d",
          "sha1": "3bc5b8f6dc031e5b4c828c749d663eeaa98bb4c8",
          "md5": "663f91059eca6de486583a96acf319e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.3-fabric-0.11.0-sources.jar",
          "url": "guilib-26.3-fabric-0.11.0-sources.jar",
          "size": 1531891,
          "sha512": "5fcab6e01d317f8b94b8dd810e737578edc074271191dcea7a5148fb886e4ecef38d884b828a8b369cf686798d744c54862e33a254848245c40dd840b65cfc74",
          "sha256": "40dcc66288521878d47be3cf9322d2612be39ddd09586adf029c628dc43fd436",
          "sha1": "82b0166281c0c433873db5aaac023df1dee65aeb",
          "md5": "b9d1dfb68b109bd539016ba33efa3c61"
        }
      ]
    }
  ]
}
