{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.1.jar",
          "url": "guilib-26.1.2-fabric-0.1.1.jar",
          "size": 2470639,
          "sha512": "088816cd22c7303d6d310f115a175a4ee5095c3b3bd396647c42de574c65a55c9ba3132dcbf36e9d17d85bf768280e0693ac2dddb402ad6ecc92f6ae65fe1cf0",
          "sha256": "2c08e6d9dd38658b83885d4dcb06298f9b5ee7672c392d64ad5cfeeb682df3a9",
          "sha1": "b34acbfeaaad8b78361e3e7258fdc3523e6e104f",
          "md5": "6076dc7127393a4667ce3ff1a188eda1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.1.jar",
          "url": "guilib-26.1.2-fabric-0.1.1.jar",
          "size": 2470639,
          "sha512": "088816cd22c7303d6d310f115a175a4ee5095c3b3bd396647c42de574c65a55c9ba3132dcbf36e9d17d85bf768280e0693ac2dddb402ad6ecc92f6ae65fe1cf0",
          "sha256": "2c08e6d9dd38658b83885d4dcb06298f9b5ee7672c392d64ad5cfeeb682df3a9",
          "sha1": "b34acbfeaaad8b78361e3e7258fdc3523e6e104f",
          "md5": "6076dc7127393a4667ce3ff1a188eda1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.1-sources.jar",
          "url": "guilib-26.1.2-fabric-0.1.1-sources.jar",
          "size": 1340377,
          "sha512": "e0d2dd97dfdc5ee20b35c0a261d0c1743fe5d6b4c9228bd453fdf1095cc923d770dd9c19757aa12516b72614174bff37c3d94eb004f82d5437d094b5473ff57f",
          "sha256": "b524b0ad2f88c5f05cee22a8b961f43c64b431914a685ca3508b22801a3dceec",
          "sha1": "490a73fbe17628074b65db46fb60c8758a4ff6e8",
          "md5": "f30994fa27849b5000a6f9e5aed4adb3"
        }
      ]
    }
  ]
}
