{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.4.jar",
          "url": "guilib-26.1.2-fabric-0.12.4.jar",
          "size": 3384184,
          "sha512": "cbf95e4c9299713d8a662c67bd80b3d7651cc67991ee3dea0913a23ae92ebef788aa4f3d755b4a4dc792840e433f6b965c43944fb199642c21336737170e2c86",
          "sha256": "e1fb2e8638b54f27ca333dd975177aba1d1690c83cbdc0d8c02d22b088d1e1b6",
          "sha1": "1bde38d51399908225bfd15ad09e1bf899487099",
          "md5": "2b24ecdf1b0e05fc94bb9e7bc4f14ea5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.4.jar",
          "url": "guilib-26.1.2-fabric-0.12.4.jar",
          "size": 3384184,
          "sha512": "cbf95e4c9299713d8a662c67bd80b3d7651cc67991ee3dea0913a23ae92ebef788aa4f3d755b4a4dc792840e433f6b965c43944fb199642c21336737170e2c86",
          "sha256": "e1fb2e8638b54f27ca333dd975177aba1d1690c83cbdc0d8c02d22b088d1e1b6",
          "sha1": "1bde38d51399908225bfd15ad09e1bf899487099",
          "md5": "2b24ecdf1b0e05fc94bb9e7bc4f14ea5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.12.4-sources.jar",
          "url": "guilib-26.1.2-fabric-0.12.4-sources.jar",
          "size": 1552365,
          "sha512": "eb30a5c67619dc7d16e40f40eae8f3944b983bec14e412a0cb0828ce3877ff07dbc3116b82240519ed5a5adf9463118553fe313b19aa95473730486c38f5b131",
          "sha256": "8bd1f66378de3c73fdada3d5c55a3636e58077032daab7b210e76a8b9a9d614a",
          "sha1": "2cc97d103e306f69ab64876ee837c60fe653063d",
          "md5": "42c60b7b835830c80c10f7e6bbbe1214"
        }
      ]
    }
  ]
}
