{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.3-fabric",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.0.jar",
          "url": "guilib-26.3-fabric-0.12.0.jar",
          "size": 3352804,
          "sha512": "4f86c528973589c7139ae2b5b0a64b0fca0327266829ad99a182d05a9b9e07196146335db4ac0213f316cb0a2cfe8176da17f86fdc8cd82e2245e6eb5eb68d77",
          "sha256": "bb74c41e8be0e5ca089f7fc397489b9ccfb152df001a66dbc0cbe157b4f3b244",
          "sha1": "6332283830bd98123db9c66ecba7291d71c7219a",
          "md5": "eb7533477a509a8ad7e6a96901012831"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.0.jar",
          "url": "guilib-26.3-fabric-0.12.0.jar",
          "size": 3352804,
          "sha512": "4f86c528973589c7139ae2b5b0a64b0fca0327266829ad99a182d05a9b9e07196146335db4ac0213f316cb0a2cfe8176da17f86fdc8cd82e2245e6eb5eb68d77",
          "sha256": "bb74c41e8be0e5ca089f7fc397489b9ccfb152df001a66dbc0cbe157b4f3b244",
          "sha1": "6332283830bd98123db9c66ecba7291d71c7219a",
          "md5": "eb7533477a509a8ad7e6a96901012831"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.3-fabric-0.12.0-sources.jar",
          "url": "guilib-26.3-fabric-0.12.0-sources.jar",
          "size": 1543232,
          "sha512": "955e75b6f00ba27e6a98a95e604b1bce54e726e846bf284b6b5d3de15fb81f13be91bc4da980726d76839f846ecf3af95d5d0524bcfaf2cd847ce36bf4caf7a5",
          "sha256": "0a0237af1218eb6d154f620f70263a93e4ad6467a121cd68462e8dacf1755579",
          "sha1": "ab1902e4fd2cbb98b9ccdbf60ae9d63eb69249fb",
          "md5": "248a69cb491e26e5810367783648a644"
        }
      ]
    }
  ]
}
