{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.7.0.jar",
          "url": "guilib-26.2-fabric-0.7.0.jar",
          "size": 3085610,
          "sha512": "c637d86a6dc8bfb82ffb0106716df8cc2e3263f5f17c911ce4472a4bd22d0a1106e74bba549414dd44146ff3a8dd551e15b85c382f61e760b5d252a17d3ceb87",
          "sha256": "45c4e33e8176674b55d831ecdbb937a50296eb547ba5c8501d007e0077cf50f4",
          "sha1": "47d7ac95fde846008830c125eaf9697cc3360a9e",
          "md5": "0d0cdb3f1079bdf6d0c8358e694e2725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.7.0.jar",
          "url": "guilib-26.2-fabric-0.7.0.jar",
          "size": 3085610,
          "sha512": "c637d86a6dc8bfb82ffb0106716df8cc2e3263f5f17c911ce4472a4bd22d0a1106e74bba549414dd44146ff3a8dd551e15b85c382f61e760b5d252a17d3ceb87",
          "sha256": "45c4e33e8176674b55d831ecdbb937a50296eb547ba5c8501d007e0077cf50f4",
          "sha1": "47d7ac95fde846008830c125eaf9697cc3360a9e",
          "md5": "0d0cdb3f1079bdf6d0c8358e694e2725"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.7.0-sources.jar",
          "url": "guilib-26.2-fabric-0.7.0-sources.jar",
          "size": 1481003,
          "sha512": "bf4b81e7e3a77a13c4f81d3e7de61141dd897b8376ebe241bdb3a8bc565f44ea6ad2cc040f2914ddadb50d995dce3153eec7473b611fb50d4d7637bc716e31a3",
          "sha256": "3919ad81c714c892295c8315cd89c5544caaeae39581c8f9df32b4ab05a0a569",
          "sha1": "dae9b31b8944a1a317b3f49149ea190c9f34fe62",
          "md5": "3cf89e9fed205231e968ad6be57ecb86"
        }
      ]
    }
  ]
}
