{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.1.2-fabric",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.0.jar",
          "url": "guilib-26.1.2-fabric-0.1.0.jar",
          "size": 2478669,
          "sha512": "63b6db1394b1715582e22d7c3a6922596b8cfd6db6201ad13f2a0a57d9f2ab59d0bed3f5d3142a418fad0896c903d3216fd3b9ad6c65cd60c566ecd65200cca9",
          "sha256": "0f16a8205609a8d374b5a0d37308664c3cb4c70cf3ad0161aeefc513064e0baf",
          "sha1": "63a3b8548374b61a82afd0987824379aa0bd9064",
          "md5": "09d36ca96c783a90e5e87e1d32b8fec9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.0.jar",
          "url": "guilib-26.1.2-fabric-0.1.0.jar",
          "size": 2478669,
          "sha512": "63b6db1394b1715582e22d7c3a6922596b8cfd6db6201ad13f2a0a57d9f2ab59d0bed3f5d3142a418fad0896c903d3216fd3b9ad6c65cd60c566ecd65200cca9",
          "sha256": "0f16a8205609a8d374b5a0d37308664c3cb4c70cf3ad0161aeefc513064e0baf",
          "sha1": "63a3b8548374b61a82afd0987824379aa0bd9064",
          "md5": "09d36ca96c783a90e5e87e1d32b8fec9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.1.2-fabric-0.1.0-sources.jar",
          "url": "guilib-26.1.2-fabric-0.1.0-sources.jar",
          "size": 1342290,
          "sha512": "139d50550873153f9b21891a29c46c6f9d5f618e9693eb68825f1bd4738bc21124c652644f01dc97b0f7ff2cf96add372ec72be17a7e86ccf42c7ce87c12de3d",
          "sha256": "c76d46a1f5ac8e3bb5a093b484d295ba945d34300d2c6b38e147bef899cfc7d1",
          "sha1": "55c155e585b2139af2e22fcf85987fd56bdbafa6",
          "md5": "07609fd0d2257bf86551577ed1f4a608"
        }
      ]
    }
  ]
}
