{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.5.jar",
          "url": "guilib-26.2-fabric-0.12.5.jar",
          "size": 3383472,
          "sha512": "884f60e4484fe25cf6cce4726fca7d9955b69f4dceb4f4c5cfac68a98cc79f9b672725307ff4b977167f8a74c60db3688c281a9f481784e52c95fd6ea0bfb5a0",
          "sha256": "66a5b878f835fc8ca5910469b4c70788260c8b8a21799bc4fd25905d306c86c2",
          "sha1": "b2196d5eb5f4cb82d666aa3caadc2d4dd4e73adc",
          "md5": "6943d83dcab25e33020364378e38628c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.5.jar",
          "url": "guilib-26.2-fabric-0.12.5.jar",
          "size": 3383472,
          "sha512": "884f60e4484fe25cf6cce4726fca7d9955b69f4dceb4f4c5cfac68a98cc79f9b672725307ff4b977167f8a74c60db3688c281a9f481784e52c95fd6ea0bfb5a0",
          "sha256": "66a5b878f835fc8ca5910469b4c70788260c8b8a21799bc4fd25905d306c86c2",
          "sha1": "b2196d5eb5f4cb82d666aa3caadc2d4dd4e73adc",
          "md5": "6943d83dcab25e33020364378e38628c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.5-sources.jar",
          "url": "guilib-26.2-fabric-0.12.5-sources.jar",
          "size": 1552628,
          "sha512": "287c3560134360524dd7255681bb6840f64f1c08c98d7d83dc6711b5474e8788f500e266ad58877fc91a624ab64c297c9259d7b372fa62d5aae1a4db12b10ede",
          "sha256": "6a234234e60c8fcfe628009da4269be69ab32e75e278ec817ce396e3e2e5354f",
          "sha1": "bc8120d6ff21e93e8a955e9e4aa3ddba928bf9f2",
          "md5": "3c850f49d32ff78f9e2cdccb66e6029a"
        }
      ]
    }
  ]
}
