{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.2.jar",
          "url": "guilib-26.2-fabric-0.12.2.jar",
          "size": 3366264,
          "sha512": "1754f63e3a9be020246131fc08396f56331e2eb3f76bbe53b4cb34ab0695027423bb0faf39fb6c50bdff2774bd3c0ee16cc9deedf7ecf889c8fb72d77ea40d8e",
          "sha256": "aec7d81f3ec82d81a3a5d16962aae1fbc141bd8fd45f444217750e3658a3d895",
          "sha1": "472f830f31beb11d9d4b784d1fffc66370baca5a",
          "md5": "ec8543e73adf89e8cec1db6bc91fe805"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.2.jar",
          "url": "guilib-26.2-fabric-0.12.2.jar",
          "size": 3366264,
          "sha512": "1754f63e3a9be020246131fc08396f56331e2eb3f76bbe53b4cb34ab0695027423bb0faf39fb6c50bdff2774bd3c0ee16cc9deedf7ecf889c8fb72d77ea40d8e",
          "sha256": "aec7d81f3ec82d81a3a5d16962aae1fbc141bd8fd45f444217750e3658a3d895",
          "sha1": "472f830f31beb11d9d4b784d1fffc66370baca5a",
          "md5": "ec8543e73adf89e8cec1db6bc91fe805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.12.2-sources.jar",
          "url": "guilib-26.2-fabric-0.12.2-sources.jar",
          "size": 1548136,
          "sha512": "d87e1c66fe57aef9c1fca99abd43dbfe296f20c0c6efa12b8ad2977ae00c54b706841135a494fb26561c442f6ebc40e0b24c22be13923fbfce24ec36419466e0",
          "sha256": "3753f677bbd03493631c42b65622c9c5265e56a30e0ea49d703d69d263eac792",
          "sha1": "d7f6d4120ffb8ed17ebc31c94580bba691e02d05",
          "md5": "016a7561e1c268a72ef16537b27d3af6"
        }
      ]
    }
  ]
}
