{
  "formatVersion": "1.1",
  "component": {
    "group": "net.sbo",
    "module": "guilib-26.2-fabric",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.5.0.jar",
          "url": "guilib-26.2-fabric-0.5.0.jar",
          "size": 3026663,
          "sha512": "928ee7e01481e69348f00ea15a4ca780f3592d9fdbaea9b62436a6ad5f7610e583bb99c5846fc095a1f9bbeba99f7818a9f65ec5beda96a4ad270ed0c1e7edfb",
          "sha256": "6c866704aa675c4ee280e6c6ce02e41d790c065625672744dff65b316e174420",
          "sha1": "e00b5eb73220db53e3508f71d572598a8e46b79c",
          "md5": "55739496fd7aef39988234754404d737"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "com.github.weisj",
          "module": "jsvg",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guilib-26.2-fabric-0.5.0.jar",
          "url": "guilib-26.2-fabric-0.5.0.jar",
          "size": 3026663,
          "sha512": "928ee7e01481e69348f00ea15a4ca780f3592d9fdbaea9b62436a6ad5f7610e583bb99c5846fc095a1f9bbeba99f7818a9f65ec5beda96a4ad270ed0c1e7edfb",
          "sha256": "6c866704aa675c4ee280e6c6ce02e41d790c065625672744dff65b316e174420",
          "sha1": "e00b5eb73220db53e3508f71d572598a8e46b79c",
          "md5": "55739496fd7aef39988234754404d737"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guilib-26.2-fabric-0.5.0-sources.jar",
          "url": "guilib-26.2-fabric-0.5.0-sources.jar",
          "size": 1464719,
          "sha512": "e49e0b1c1eabd637065b546fdc1f6885ba148ba5bc2c9800a10f98d3e1e5046bf221588dd00ce8f2e6c9a1c6e0953b316e562d07c56069a2b1b48cf240afc041",
          "sha256": "f4300c8ee97173f7a30063ae4df0630aa0ffb031770811f9e9bb22cbb0378d3d",
          "sha1": "d00e555e0eda418cfe34eb04f0539ecb03252369",
          "md5": "b122e091cfa65e185f217bd0f8fd4248"
        }
      ]
    }
  ]
}
